#pragma once
#define VIAL_KEYBOARD_UID {0x57, 0xDC, 0x1A, 0x10, 0xF9, 0x3C, 0xDF, 0x0}
#define VIAL_UNLOCK_COMBO_ROWS { 1, 2}
#define VIAL_UNLOCK_COMBO_COLS { 1, 2} 

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define DYNAMIC_KEYMAP_MACRO_COUNT 32